/*
 * tree.c - Arc Lab
 * 
 * DO NOT EDIT THIS FILE.
 *
 * Benchmark using a AVL tree to cause a pointer chase.
 *
 */

#include <stdlib.h>
#include <stdio.h>
#include <sys/time.h>
#include <assert.h>
#include <time.h>
#include <unistd.h>
#include <stdbool.h>
#include "archlab.h"

/* do not change the following */
#define N 10
#define SEED 18600
#define PRIME 4093
static void usage(char *prog);

int modpow(int a, int exponent, int prime) {
    if (exponent == 0) {
        return 1;
    } else if(exponent % 2 == 1) {
        int tmp = modpow(a, exponent - 1, prime);
        return (tmp * a) % prime;
    } else {
        int tmp = modpow(a, exponent/2, prime);
        return (tmp * tmp) % prime;
    }
}

int main(int argc, char **argv)
{
    char c;
    bool gem5 = false;
    int ret = 0;
    int seed = SEED;
    int a[N];
    int e[N];
    int res[N];
    while ((c = getopt(argc, argv, "hgr")) != EOF) {
        switch (c) {
            case 'h': 
                usage(argv[0]);
                exit(0);
            case 'g':
                printf("gem5 routines\n");
                gem5 = true;
                break;
            case 'r':
                printf("random initialization\n");
                //fixme
                break;
            default:
                usage(argv[0]);
                exit(1);
        }
    }
    srand(seed);
    printf("seed: %d\n", seed);
    ROI_START(gem5);
    for (int i = 0; i < N; i++) {
        a[i] = (rand() % PRIME);
        e[i] = (rand() % PRIME);
        res[i] = modpow(a[i], e[i], PRIME);
    }
    ROI_END(gem5);
    for (int i = 0; i < N; i++) {
        printf("%d^%d mod %d = %d\n", a[i], e[i], PRIME, res[i]);
    }
    printf("Verified!");
    return ret;
}

/*
 * usage - Describe the command line arguments 
 */
static void usage(char *prog)
{
    fprintf(stderr, "Usage %s [-hg]\n", prog);
    fprintf(stderr, "Options\n");
    fprintf(stderr, "\t-h       Print this message.\n");
    fprintf(stderr, "\t-g       Enable gem5 regio of interest.\n");
}

