/*
 * tree.c - Arc Lab
 * 
 * DO NOT EDIT THIS FILE.
 *
 * Benchmark using a AVL tree to cause a pointer chase.
 *
 */

#include <stdlib.h>
#include <stdio.h>
#include <sys/time.h>
#include <assert.h>
#include <time.h>
#include <unistd.h>
#include <stdbool.h>
#include "archlab.h"
#include "avl.h"

/* do not change the following */
#define N 127
#define SEED 18600

static void usage(char *prog);

/*
 * Note:
 * We maintain a tree of integers. To avoid uneeded memory allocations we store
 * the integer directly inside the void*.
 * Conseuqntly this causes a lot of gcc warnings since we are deliberately
 * casting void* to int and back again. We can ignaore those warning as long as:
 * - int is smaller than void*
 * - we never dereference those "pointers"
 */

int comparison_function(const void *pa, const void *pb, void *params) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
    const int a = (int)pa;
    const int b = (int)pb;
#pragma GCC diagnostic pop

    if (a < b) {
        return -1;
    } else if (a > b) {
        return +1;
    } else {
        return 0;
    }
}

int main(int argc, char **argv)
{
    char c;
    bool gem5 = false;
    int ret = 0;
    int seed = SEED;
    while ((c = getopt(argc, argv, "hgr")) != EOF) {
        switch (c) {
            case 'h': 
                usage(argv[0]);
                exit(0);
            case 'g':
                printf("gem5 routines\n");
                gem5 = true;
                break;
            case 'r':
                printf("random initialization\n");
                //fixme
                break;
            default:
                usage(argv[0]);
                exit(1);
        }
    }
    srand(seed);    
    struct avl_table *tree = avl_create(comparison_function, NULL, NULL);    
    ROI_START(gem5);
    for (int i = 0; i < N; i++) {
        int number = rand();
        if(number == 0) {
            i--;
            continue;
        }
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
        if(avl_insert(tree, (void*)number) == (void*)number) {
#pragma GCC diagnostic pop
            i--;
        }
    }
    struct avl_traverser trav;
    avl_t_first(&trav, tree);
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
    int sum = 0;
    int number;
    while ((number = (int)avl_t_cur(&trav))) { 
#pragma GCC diagnostic pop
        sum += number;
        if(!gem5) {
            printf("%d ", number);
        }
        avl_t_next(&trav);
    }
    ROI_END(gem5);
    printf("\n sum: %d\n", sum);
    avl_destroy(tree, NULL);
    if(sum == 1931303270) {
        printf("Verified!");
    }
    return ret;
}

/*
 * usage - Describe the command line arguments 
 */
static void usage(char *prog)
{
    fprintf(stderr, "Usage %s [-hg]\n", prog);
    fprintf(stderr, "Options\n");
    fprintf(stderr, "\t-h       Print this message.\n");
    fprintf(stderr, "\t-g       Enable gem5 regio of interest.\n");
}

